/*
 * This file is generated by jOOQ.
 */
package com.github.blacky.subscriber_lifecycle.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Call implements Serializable {

    private static final long serialVersionUID = -816924605;

    private Long      id;
    private Long      subscriberId;
    private Timestamp created;
    private Timestamp updated;

    public Call() {}

    public Call(Call value) {
        this.id = value.id;
        this.subscriberId = value.subscriberId;
        this.created = value.created;
        this.updated = value.updated;
    }

    public Call(
        Long      id,
        Long      subscriberId,
        Timestamp created,
        Timestamp updated
    ) {
        this.id = id;
        this.subscriberId = subscriberId;
        this.created = created;
        this.updated = updated;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSubscriberId() {
        return this.subscriberId;
    }

    public void setSubscriberId(Long subscriberId) {
        this.subscriberId = subscriberId;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Timestamp getUpdated() {
        return this.updated;
    }

    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Call (");

        sb.append(id);
        sb.append(", ").append(subscriberId);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
