/*
 * This file is generated by jOOQ.
 */
package com.github.blacky.subscriber_lifecycle.jooq;


import com.github.blacky.subscriber_lifecycle.jooq.tables.Call;
import com.github.blacky.subscriber_lifecycle.jooq.tables.Subscriber;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CALL_PKEY = Indexes0.CALL_PKEY;
    public static final Index SUBSCRIBER_MSISDN_KEY = Indexes0.SUBSCRIBER_MSISDN_KEY;
    public static final Index SUBSCRIBER_PKEY = Indexes0.SUBSCRIBER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CALL_PKEY = Internal.createIndex("call_pkey", Call.CALL, new OrderField[] { Call.CALL.ID }, true);
        public static Index SUBSCRIBER_MSISDN_KEY = Internal.createIndex("subscriber_msisdn_key", Subscriber.SUBSCRIBER, new OrderField[] { Subscriber.SUBSCRIBER.MSISDN }, true);
        public static Index SUBSCRIBER_PKEY = Internal.createIndex("subscriber_pkey", Subscriber.SUBSCRIBER, new OrderField[] { Subscriber.SUBSCRIBER.ID }, true);
    }
}
