/*
 * This file is generated by jOOQ.
 */
package com.github.blacky.subscriber_lifecycle.jooq;


import com.github.blacky.subscriber_lifecycle.jooq.tables.Call;
import com.github.blacky.subscriber_lifecycle.jooq.tables.Subscriber;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 2098245888;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.call</code>.
     */
    public final Call CALL = com.github.blacky.subscriber_lifecycle.jooq.tables.Call.CALL;

    /**
     * The table <code>public.subscriber</code>.
     */
    public final Subscriber SUBSCRIBER = com.github.blacky.subscriber_lifecycle.jooq.tables.Subscriber.SUBSCRIBER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CALL_ID_SEQ,
            Sequences.CALL_SUBSCRIBER_ID_SEQ,
            Sequences.SUBSCRIBER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Call.CALL,
            Subscriber.SUBSCRIBER);
    }
}
