/*
 * This file is generated by jOOQ.
 */
package com.github.blacky.subscriber_lifecycle.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.call_id_seq</code>
     */
    public static final Sequence<Long> CALL_ID_SEQ = new SequenceImpl<Long>("call_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.call_subscriber_id_seq</code>
     */
    public static final Sequence<Long> CALL_SUBSCRIBER_ID_SEQ = new SequenceImpl<Long>("call_subscriber_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.subscriber_id_seq</code>
     */
    public static final Sequence<Long> SUBSCRIBER_ID_SEQ = new SequenceImpl<Long>("subscriber_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
