/*
 * This file is generated by jOOQ.
 */
package com.github.blacky.subscriber_lifecycle.jooq;


import com.github.blacky.subscriber_lifecycle.jooq.tables.Subscriber;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.subscriber</code>.
     */
    public static final Subscriber SUBSCRIBER = Subscriber.SUBSCRIBER;
}
