/*
 * This file is generated by jOOQ.
 */
package com.github.blacky.subscriber_lifecycle.jooq.tables.records;


import com.github.blacky.subscriber_lifecycle.jooq.enums.Status;
import com.github.blacky.subscriber_lifecycle.jooq.tables.Subscriber;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubscriberRecord extends UpdatableRecordImpl<SubscriberRecord> implements Record6<Long, String, String, String, Long, Status> {

    private static final long serialVersionUID = -461147972;

    /**
     * Setter for <code>public.subscriber.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.subscriber.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.subscriber.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.subscriber.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.subscriber.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.subscriber.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.subscriber.msisdn</code>.
     */
    public void setMsisdn(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.subscriber.msisdn</code>.
     */
    public String getMsisdn() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.subscriber.balance</code>.
     */
    public void setBalance(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.subscriber.balance</code>.
     */
    public Long getBalance() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.subscriber.status</code>.
     */
    public void setStatus(Status value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.subscriber.status</code>.
     */
    public Status getStatus() {
        return (Status) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, Long, Status> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, Long, Status> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Subscriber.SUBSCRIBER.ID;
    }

    @Override
    public Field<String> field2() {
        return Subscriber.SUBSCRIBER.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Subscriber.SUBSCRIBER.LAST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Subscriber.SUBSCRIBER.MSISDN;
    }

    @Override
    public Field<Long> field5() {
        return Subscriber.SUBSCRIBER.BALANCE;
    }

    @Override
    public Field<Status> field6() {
        return Subscriber.SUBSCRIBER.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public String component4() {
        return getMsisdn();
    }

    @Override
    public Long component5() {
        return getBalance();
    }

    @Override
    public Status component6() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public String value4() {
        return getMsisdn();
    }

    @Override
    public Long value5() {
        return getBalance();
    }

    @Override
    public Status value6() {
        return getStatus();
    }

    @Override
    public SubscriberRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SubscriberRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public SubscriberRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public SubscriberRecord value4(String value) {
        setMsisdn(value);
        return this;
    }

    @Override
    public SubscriberRecord value5(Long value) {
        setBalance(value);
        return this;
    }

    @Override
    public SubscriberRecord value6(Status value) {
        setStatus(value);
        return this;
    }

    @Override
    public SubscriberRecord values(Long value1, String value2, String value3, String value4, Long value5, Status value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubscriberRecord
     */
    public SubscriberRecord() {
        super(Subscriber.SUBSCRIBER);
    }

    /**
     * Create a detached, initialised SubscriberRecord
     */
    public SubscriberRecord(Long id, String firstName, String lastName, String msisdn, Long balance, Status status) {
        super(Subscriber.SUBSCRIBER);

        set(0, id);
        set(1, firstName);
        set(2, lastName);
        set(3, msisdn);
        set(4, balance);
        set(5, status);
    }
}
